set(amg_PUBLIC_HEADERS
  DirectInterpolation.h
  InitFunctor.h
  intersection_size.h
  LevelGenerator.h
  PretendCoarsening.h
  StandardCoarsening.h
  StandardCoarseningInterpolationConnection.h
  StandardCoarseningSettings.h
  StandardInterpolation.h
  TransposeFunctor.h
  TripleProduct.h
  TripleProductImpl.h
  typedefs.h
)
