set(polynomials_SOURCES
  lagrangecoeff10.cc
  lagrangecoeff13.cc
  lagrangecoeff16.cc
  lagrangecoeff19.cc
  lagrangecoeff2.cc
  lagrangecoeff5.cc
  lagrangecoeff8.cc
  lagrangecoeff11.cc
  lagrangecoeff14.cc
  lagrangecoeff17.cc
  lagrangecoeff1.cc
  lagrangecoeff3.cc
  lagrangecoeff6.cc
  lagrangecoeff9.cc
  lagrangecoeff12.cc
  lagrangecoeff15.cc
  lagrangecoeff18.cc
  lagrangecoeff20.cc
  lagrangecoeff4.cc
  lagrangecoeff7.cc
  lagrangecoeff.cc
  polycoeff.cc
  lagrangepolynomial.cc
  legansatzpolynomial.cc)

set(polynomials_PUBLIC_HEADERS 
  polycoeff.h
  lagrangecoeff.h
  legansatzpolynomial.h
  lagrangepolynomial.h
  legendrepolynomial.h
  lagrangecoeff10.h
  lagrangecoeff13.h
  lagrangecoeff16.h
  lagrangecoeff19.h
  lagrangecoeff2.h
  lagrangecoeff5.h
  lagrangecoeff8.h
  lagrangecoeff11.h
  lagrangecoeff14.h
  lagrangecoeff17.h
  lagrangecoeff1.h
  lagrangecoeff3.h
  lagrangecoeff6.h
  lagrangecoeff9.h
  lagrangecoeff12.h
  lagrangecoeff15.h
  lagrangecoeff18.h
  lagrangecoeff20.h
  lagrangecoeff4.h
  lagrangecoeff7.h
  )
