#!/bin/sh

# Copyright (C) 2011-2021 Vincent Heuveline
#
# HiFlow3 is free software: you can redistribute it and/or modify it under the
# terms of the European Union Public Licence (EUPL) v1.2 as published by the
#/ European Union or (at your option) any later version.
#
# HiFlow3 is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the European Union Public Licence (EUPL) v1.2 for more
# details.
#
# You should have received a copy of the European Union Public Licence (EUPL) v1.2
# along with HiFlow3.  If not, see <https://joinup.ec.europa.eu/page/eupl-text-11-12>.

################################################################################
# Template simulator to Dakota system call script
# =================================================
#
# For applying Dakota to HiFlow3
# See Advanced Simulation Code Interfaces chapter in Dakota's User's Manual
#
# Author Jonas Kratzke
################################################################################

# $1 is params.in FROM Dakota
# $2 is results.out returned to Dakota

# --------------
# PRE-PROCESSING
# --------------
# Incorporate the parameters from DAKOTA into the template, creating
# a specific input parameter file.

dprepro $1 hiflow_params_template.xml hiflow_params_specific.xml

# --------
# ANALYSIS
# --------

mpirun -n <procs> application_binary hiflow_params_specific.xml

# ---------------
# POST-PROCESSING
# ---------------

# Extract a number of resulting values from the simulation output.
# In the case of a single Quantity of interest value, $2 should contain
# just the value.
your_post_proc_script > $2

